[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.17.0"
  NEXT_TELEMETRY_DISABLED = "1"
  # Dummy DATABASE_URL for build process (Prisma needs it to generate client)
  DATABASE_URL = "postgresql://dummy:dummy@dummy:5432/dummy"
  # Common environment variables for build
  NEXTAUTH_URL = "https://dummy.netlify.app"
  NEXTAUTH_SECRET = "dummy-secret-for-build-only"
  # Skip validations during build
  SKIP_ENV_VALIDATION = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs" 