[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  DATABASE_URL = "file:./prod.db"
  PRISMA_FORCE_GENERATION = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration pour Prisma Studio
[[redirects]]
  from = "/studio/*"
  to = "http://localhost:5555/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Cache configuration
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      ".next/cache",
      "prisma/migrations",
      "*.db"
    ]

# Commandes de build et d'initialisation
[build.lifecycle]
  onBuild = "npm run netlify:init"
  onSuccess = "npx prisma generate && npx prisma studio" 