[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmI5OThiOTQtZjA3Yi00MGQ2LTgwMDEtNTE0Njk0NzE1NmEwIiwidGVuYW50X2lkIjoiYWM3OGZlOGFiNjMwZGUzYTliOGU4ZjIwNDNkMDQ2OTQ2MDlkMTQ4Zjc4MmQxOTM2NzIzNzgzMGQ1ZDUyNzVkMSIsImludGVybmFsX3NlY3JldCI6IjRjMWVmZmQzLTViNDMtNDc4YS1iMDhkLWQyZjdkYjRlM2VlNCJ9.njA8oim31DpetqngDDkoXUJShjVGn9ZPUWTVNzWX4uo"
  DIRECT_URL = "postgresql://bnk2025_user:Ue4Ue4Ue4@ep-polished-dawn-a5xv1qlp.eu-central-1.aws.neon.tech/bnk2025?sslmode=require"
  PRISMA_FORCE_GENERATION = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration pour Prisma Studio
[[redirects]]
  from = "/studio/*"
  to = "http://localhost:5555/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Cache configuration
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      ".next/cache",
      "prisma/migrations"
    ]

# Commandes de build et d'initialisation
[build.lifecycle]
  onBuild = """
    npx prisma generate && \
    npx prisma migrate deploy && \
    npm run netlify:init
  """
  onSuccess = "npx prisma studio" 